import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto('http://localhost:4321', { waitUntil: 'networkidle2', timeout: 30000 });
await new Promise(r => setTimeout(r, 2000));
await page.screenshot({ path: 'temporary screenshots/screenshot-7-cta-section.png', clip: { x: 0, y: 7900, width: 1440, height: 900 } });
await page.screenshot({ path: 'temporary screenshots/screenshot-8-areas.png', clip: { x: 0, y: 4500, width: 1440, height: 900 } });
console.log('Done');
await browser.close();
